### ISSUE TITLE
Not login at new version of ChatGPT [BUG]

### ISSUE THREAD

**Issue by isMMa** [ugorsahin/ChatGPT_Automation#18]
The scripts send:

```
Traceback (most recent call last):
  File "code.py", line 14, in <module>
    chatgpt = ChatGPT_Client(OPENAI_EMAIL, OPENAI_PASSWORD)
  File "/usr/local/lib/python3.8/site-packages/chatgpt_automation/chatgpt_client.py", line 72, in __init__
    self.login(username, password)
  File "/usr/local/lib/python3.8/site-packages/chatgpt_automation/chatgpt_client.py", line 146, in login
    continue_button.click()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=114.0.5735.133)
```

ChatGPT change the main login page:

![imagen](https://github.com/ugorsahin/ChatGPT_Automation/assets/6026178/5ad47b53-7eb9-42fe-a5c7-c41ad4cdfaa2)

**Comment by ugorsahin** [comment]
Kudos mate, With commit [cb0214f](https://github.com/ugorsahin/ChatGPT_Automation/commit/cb0214ff18414e472c5c2e9a8fec1bbb57c23571), you should be able to continue as expected. Let me know if everything is working on your end so I can close the issue.

**Comment by isMMa** [comment]
Thanks for the job. It is a great project.

**Comment by isMMa** [comment]
I think it keeps failing, it keeps giving me this error, after reinstalling in my Docker

```
Traceback (most recent call last):
  File "code.py", line 14, in <module>
    chatgpt = ChatGPT_Client(OPENAI_EMAIL, OPENAI_PASSWORD)
  File "/usr/local/lib/python3.8/site-packages/chatgpt_automation/chatgpt_client.py", line 72, in __init__
    self.login(username, password)
  File "/usr/local/lib/python3.8/site-packages/chatgpt_automation/chatgpt_client.py", line 146, in login
    continue_button.click()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=114.0.5735.133)
```

# syntax=docker/dockerfile:1

FROM python:3.8

RUN apt-get update -y
RUN apt install python3-pip -y

RUN pip install python-dotenv
RUN pip install undetected-chromedriver

RUN cd /tmp/
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt install ./google-chrome-stable_current_amd64.deb -y


RUN pip install git+https://github.com/ugorsahin/ChatGPT_Automation

CMD tail -f /dev/null

**Comment by ugorsahin** [comment]
I am afraid you are using cached version, try to pass `--no-cache-dir` to pip install

**Comment by Karajan421** [comment]
Hey there! Thanks for everything you're doing, it's really been a great help on some prototype projects :) 

I'm encountering the same issue as isMMa. Reinstalled with the recommended argument but to no avail. I checked the package script, it is up to date but the issue persists :(

**Comment by isMMa** [comment]
Thanks, now its works. You can use my Dockerfile to your project if you need. Great Job!

**Comment by ugorsahin** [comment]
> I'm encountering the same issue as isMMa. Reinstalled with the recommended argument but to no avail. I checked the package script, it is up to date but the issue persists :(

@Karajan421  I don't know how it fails in your environment but it shouldn't be the same error anymore. Feel free to open an issue with a screenshot or exception information I would be happy to help
