### ISSUE TITLE
if you use chrome 114 , it can't run

### ISSUE THREAD

**Issue by moonandlake123** [ugorsahin/ChatGPT_Automation#20]
2023/07/10 12:49:15 WARNING Windows detected, no version number is provided, default: 112
Traceback (most recent call last):
  File "d:\Documents\new2.py", line 3, in <module>
    chatgpt = ChatGPT_Client('2208204392@qq.com','819Syf131')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\chatgpt_automation\chatgpt_client.py", line 62, in __init__
    self.browser = uc.Chrome(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 443, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 49, in __init__
    super().__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 54, in __init__
    super().__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 674, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:52952
from session not created: This version of ChromeDriver only supports Chrome version 112
Current browser version is 114.0.5735.199
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0099DCE3+50899]
	(No symbol) [0x0092E111]
	(No symbol) [0x00835588]
	(No symbol) [0x0085570C]
	(No symbol) [0x0084F5B1]
	(No symbol) [0x0084F391]
	(No symbol) [0x00881FFE]
	(No symbol) [0x00881CEC]
	(No symbol) [0x0087B6F6]
	(No symbol) [0x00857708]
	(No symbol) [0x0085886D]
	GetHandleVerifier [0x00C03EAE+2566302]
	GetHandleVerifier [0x00C392B1+2784417]
	GetHandleVerifier [0x00C3327C+2759788]
	GetHandleVerifier [0x00A35740+672048]
	(No symbol) [0x00938872]
	(No symbol) [0x009341C8]
	(No symbol) [0x009342AB]
	(No symbol) [0x009271B7]
	BaseThreadInitThunk [0x761D7D59+25]
	RtlInitializeExceptionChain [0x7739B74B+107]
	RtlClearBits [0x7739B6CF+191]

**Comment by ugorsahin** [comment]
Hello, you need to pass argument `driver_version = 114` to constructor. Pass 114 as integer and it should work

**Comment by neslex** [comment]
I'm getting the same error, have spent hours trying to get this working.

**Comment by moonandlake123** [comment]
thanks for your advise



                       
原始邮件
                       
                     

发件人："ugorsahin"< ***@***.*** &gt;;

发件时间：2023/7/11 0:36

收件人："ugorsahin/ChatGPT_Automation"< ***@***.*** &gt;;

抄送人："moonandlake123"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [ugorsahin/ChatGPT_Automation] if you use chrome 114 , it can'trun (Issue #20)





Hello, you need to pass argument driver_version = 114 to constructor. Pass 114 as integer and it should work

**Comment by moonandlake123** [comment]
@ugorsahin  I try your advise,but i get the same error.The error mean the chrome driver is only support the chrome 112,I try to update the chrome driver and undetected_chromedriver but it still don't run

**Comment by medinm0** [comment]
Ran into this issue too. What ended up working for me was deleting the following folder. This took forever to figure out: C:\Users\YOURUSERACCOUNT\AppData\Roaming\undetected_chromedriver

Then everything started working again. If need be you can get the latest chrome driver from the following link: https://chromedriver.chromium.org/downloads .

**Comment by ugorsahin** [comment]
Assuming that the new version of undetected-chromedriver and new releases in this repository solved the problem, I close this issue due to inactivity.
